### ISSUE TITLE
Mastering Algorithms in C

### ISSUE THREAD

**Issue by andrewvy** [andrewvy/sketches#3]
Book: [The one by O'reilly.](http://shop.oreilly.com/product/9781565924536.do)

This, paired with [K&R](https://github.com/andrewvy/sketches/issues/1). :100: 
# Data Structures
- [ ] Linked List
- [ ] Stacks and Queues
- [ ] Sets
- [ ] Hash Tables
- [ ] Trees
- [ ] Heaps and Priority Queues
- [ ] Graphs
# Algorithms
- [ ] Sorting and Searching
- [ ] Numerical Methods
- [ ] Data Compression
- [ ] Data Encryption
- [ ] Graph Algorithms
- [ ] Geometric Algorithms
