### ISSUE TITLE
Mini Virtual Machine in C

### ISSUE THREAD

**Issue by andrewvy** [andrewvy/sketches#4]
https://github.com/andrewvy/sketches/tree/master/virtual_machine_in_c
- [x] Add file functionality (Loading programs from a file)
- [x] Stack Pointer OoB checking 
- [ ] Add branching instructions (borred from [DCPU spec](https://raw.githubusercontent.com/gatesphere/demi-16/master/docs/dcpu-specs/dcpu-1-7.txt))
  - [ ] IFB - performs next instruction only if (b&a)!=0
  - [ ] IFC - performs next instruction only if (b&a)==0
  - [x] IFE - performs next instruction only if b==a 
  - [x] IFN - performs next instruction only if b!=a 
  - [x] IFG - performs next instruction only if b>a 
  - [x] IFL - performs next instruction only if b<a
